### ISSUE TITLE
sudo setup.py install ISSUE

### ISSUE THREAD

**Issue by ipaidthebills** [MyMeepSQL/OmegaPSToolkit#4]
I have followed all instruction and keep getting this error= " [CRITICAL]   A current(s) module(s) was not installed, run the 'setup.py' for install it. (sudo setup.py install) "

Same issue even after running= (sudo setup.py install) 

Im running the latest and fully updated Kali. Any help would be great.

**Comment by MyMeepSQL** [comment]
I’ll try to fix it

**Comment by stevesmithnz** [comment]
I am also having the same issue and really excited to test out your tools

**Comment by pi198pi** [comment]
having the same issue waiting your update 
good luck

**Comment by MyMeepSQL** [comment]
Okay i fix it (normaly). Now delete all file of OmegaDSToolkit and reinstall it from Github (sudo git clone https://github.com/MyMeepSQL/OmegaDSToolkit.git) and remake all setep

**Comment by ipaidthebills** [comment]
> Okay I fix it (normaly). Now delete all files of OmegaDSToolkit and reinstall it from Github (sudo git clone https://github.com/MyMeepSQL/OmegaDSToolkit.git), remake all steps and tell me if the issue was repair

Woohoo It worked perfectly. Thanks @MyMeepSQL

**Comment by MyMeepSQL** [comment]
Nice thanks for your repport. Have a nice day
